# Generated by Django 2.0.6 on 2018-06-29 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_username', models.CharField(max_length=150)),
                ('is_friend', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.AddField(
            model_name='relationship',
            name='from_username',
            field=models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, related_name='relation_set', to='split.Profile'),
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('from_username', 'to_username')},
        ),
    ]
