# Generated by Django 2.0.6 on 2018-06-29 04:18

from django.db import migrations, models
import django.db.models.deletion

from split.models import Profile


class Migration(migrations.Migration):
    dependencies = [
        ('split', '0002_auto_20180629_0355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationship',
            old_name='to_username',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='relationship',
            old_name='from_username',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('user', 'username')},
        ),
    ]
